services:
  eventastic-app:
    image: eventastic-app:latest
    container_name: eventastic_app
    restart: always
    env_file:
      - .env
    ports:
      - '8081:8080'
    depends_on:
      - db
      - redis
    volumes:
      - ./src/main/resources/certs/private-key.pem:/app/certs/private-key.pem
      - ./src/main/resources/certs/public-key.pem:/app/certs/public-key.pem

  db:
    image: postgres:alpine
    restart: always
    container_name: eventastic_db
    environment:
      POSTGRES_URL: ${PGURL}
      POSTGRES_HOST: ${PGHOST}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: eventastic_redis
#    command: redis-server --requirepass ${REDIS_PASSWORD} --tls-port 6379 --port 0
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
